import { NextRequest, NextResponse } from "next/server";
import { connectDB } from "@/lib/db";
import { requireAdmin } from "@/lib/api-guards";
import { Staff } from "@/lib/models/staff.model";
import { StaffRole } from "@/lib/models/constants";

// GET /api/admin/staff?role=teacher&status=active&search=jane
export async function GET(req: NextRequest) {
  const guard = await requireAdmin();
  if (!guard.ok) return guard.response;

  await connectDB();
  const params = req.nextUrl.searchParams;
  const role = params.get("role") as StaffRole | null;
  const status = params.get("status"); // "active" | "inactive" | null
  const search = params.get("search")?.trim();

  const filter: Record<string, unknown> = {};
  if (role) filter.role = role;
  if (status === "active") filter.isActive = true;
  if (status === "inactive") filter.isActive = false;
  if (search) {
    const pattern = new RegExp(search.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i");
    filter.$or = [
      { firstName: pattern },
      { lastName: pattern },
      { username: pattern },
      { staffId: pattern },
      { email: pattern },
    ];
  }

  const staff = await Staff.find(filter)
    .populate("assignedSubjects", "name code")
    .sort({ createdAt: -1 });

  return NextResponse.json({ staff });
}

// POST /api/admin/staff
// Body: { firstName, lastName, username, role?, email?, phone?, gender? }
// Password is auto-generated by the Staff model, same pattern as Student -
// returned once here as tempPassword and never recoverable afterwards.
export async function POST(req: NextRequest) {
  const guard = await requireAdmin();
  if (!guard.ok) return guard.response;

  await connectDB();
  const body = await req.json();

  try {
    const staff = new Staff({
      firstName: body.firstName,
      lastName: body.lastName,
      username: body.username,
      role: body.role || "teacher",
      email: body.email,
      phone: body.phone,
      gender: body.gender,
    });
    await staff.save();

    const tempPassword = staff.$locals.plainPassword as string | undefined;

    return NextResponse.json(
      {
        staff: {
          id: staff.id,
          staffId: staff.staffId,
          username: staff.username,
          firstName: staff.firstName,
          lastName: staff.lastName,
          role: staff.role,
        },
        tempPassword,
      },
      { status: 201 },
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to create staff member";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}
