import { NextRequest, NextResponse } from "next/server";
import { connectDB } from "@/lib/db";
import { requireAdmin } from "@/lib/api-guards";
import { Student } from "@/lib/models/student.model";
import { ClassLevel } from "@/lib/models/constants";

// GET /api/admin/students?class=JSS1&status=active&search=john
// - class: exact CLASS_LEVELS value
// - status: "active" | "inactive" (omit for both)
// - search: matches against first name, last name, or admission number
export async function GET(req: NextRequest) {
  const guard = await requireAdmin();
  if (!guard.ok) return guard.response;

  await connectDB();
  const params = req.nextUrl.searchParams;
  const classFilter = params.get("class") as ClassLevel | null;
  const status = params.get("status"); // "active" | "inactive" | null
  const search = params.get("search")?.trim();

  const filter: Record<string, unknown> = {};
  if (classFilter) filter.class = classFilter;
  if (status === "active") filter.isActive = true;
  if (status === "inactive") filter.isActive = false;
  if (search) {
    // Case-insensitive partial match across name and admission number.
    const pattern = new RegExp(search.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i");
    filter.$or = [{ firstName: pattern }, { lastName: pattern }, { admissionNumber: pattern }];
  }

  const students = await Student.find(filter).sort({ createdAt: -1 });

  return NextResponse.json({ students });
}

// POST /api/admin/students
// Body: { firstName, lastName, class, gender?, dateOfBirth?, address? }
// Password is intentionally NOT accepted here - it's auto-generated by the
// Student model's pre-validate hook (see student.model.ts).
export async function POST(req: NextRequest) {
  const guard = await requireAdmin();
  if (!guard.ok) return guard.response;

  await connectDB();
  const body = await req.json();

  try {
    const student = new Student({
      firstName: body.firstName,
      lastName: body.lastName,
      class: body.class,
      gender: body.gender,
      dateOfBirth: body.dateOfBirth,
      address: body.address,
    });
    await student.save();

    // Only readable right now, on this exact document instance - the
    // hash is what actually gets persisted.
    const tempPassword = student.$locals.plainPassword as string | undefined;

    return NextResponse.json(
      {
        student: {
          id: student.id,
          admissionNumber: student.admissionNumber,
          firstName: student.firstName,
          lastName: student.lastName,
          class: student.class,
        },
        tempPassword, // show/print this once for the admin to hand to the student
      },
      { status: 201 },
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to create student";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}
