import { ExamData } from "@/types/exam-taking";
export const examData: Record<string, ExamData> = {
  "chemistry-objective": {
    slug: "chemistry-objective",
    subject: "Chemistry",
    class: "JSS3",
    term: "First Term",
    date: "23 June 2025",
    time: "7:00 AM",
    duration: 120,
    type: "objective",
    instructions: [
      "Read all questions carefully before answering.",
      "Select the best answer for each question.",
      "Each question carries equal marks.",
    ],
    questions: [
      {
        id: 1,
        text: "What is the chemical symbol for water?",
        options: ["H2O", "CO2", "NaCl", "HCl"],
        type: "objective",
        marks: 5,
      },
      {
        id: 2,
        text: "What is the atomic number of Carbon?",
        options: ["6", "12", "14", "8"],
        type: "objective",
        marks: 5,
      },
      {
        id: 3,
        text: "Which of the following is a noble gas?",
        options: ["Oxygen", "Nitrogen", "Helium", "Hydrogen"],
        type: "objective",
        marks: 5,
      },
      {
        id: 4,
        text: "What is the pH of pure water?",
        options: ["5", "7", "9", "11"],
        type: "objective",
        marks: 5,
      },
      {
        id: 5,
        text: "Which element is represented by the symbol Fe?",
        options: ["Iron", "Fluorine", "Fermium", "Francium"],
        type: "objective",
        marks: 5,
      },
    ],
  },
  "chemistry-theory": {
    slug: "chemistry-theory",
    subject: "Chemistry",
    class: "JSS3",
    term: "First Term",
    date: "23 June 2025",
    time: "10:00 AM",
    duration: 90,
    type: "theory",
    instructions: [
      "Answer all questions in the space provided.",
      "Show all workings where necessary.",
      "Write clearly and legibly.",
      "Each question carries the marks indicated.",
    ],
    questions: [
      {
        id: 1,
        text: "Define an acid and give two examples with their chemical formulas.",
        type: "theory",
        marks: 10,
      },
      {
        id: 2,
        text: "Explain the process of photosynthesis and write the chemical equation.",
        type: "theory",
        marks: 15,
      },
      {
        id: 3,
        text: "Describe the differences between a mixture and a compound. Give two examples of each.",
        type: "theory",
        marks: 10,
      },
      {
        id: 4,
        text: "What is the periodic table? Explain how elements are arranged in the periodic table.",
        type: "theory",
        marks: 10,
      },
    ],
  },
  "physics-objective": {
    slug: "physics-objective",
    subject: "Physics",
    class: "JSS3",
    term: "First Term",
    date: "27 June 2025",
    time: "7:00 AM",
    duration: 120,
    type: "objective",
    instructions: ["All questions are compulsory.", "Choose the best answer for each question."],
    questions: [
      {
        id: 1,
        text: "What is the SI unit of force?",
        options: ["Newton", "Joule", "Watt", "Pascal"],
        type: "objective",
        marks: 5,
      },
      {
        id: 2,
        text: "What is the speed of light approximately?",
        options: ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "3 × 10¹⁰ m/s", "3 × 10⁴ m/s"],
        type: "objective",
        marks: 5,
      },
    ],
  },
  "physics-theory": {
    slug: "physics-theory",
    subject: "Physics",
    class: "JSS3",
    term: "First Term",
    date: "27 June 2025",
    time: "10:00 AM",
    duration: 90,
    type: "theory",
    instructions: [
      "Answer all questions.",
      "Show all workings and calculations.",
      "Include diagrams where necessary.",
    ],
    questions: [
      {
        id: 1,
        text: "State Newton's three laws of motion. Give one example of each law in everyday life.",
        type: "theory",
        marks: 15,
      },
      {
        id: 2,
        text: "What is energy? Explain the difference between kinetic and potential energy with examples.",
        type: "theory",
        marks: 10,
      },
    ],
  },
  "mathematics-objective": {
    slug: "mathematics-objective",
    subject: "Mathematics",
    class: "JSS3",
    term: "First Term",
    date: "25 June 2025",
    time: "9:00 AM",
    duration: 150,
    type: "objective",
    instructions: ["Answer all questions.", "Select the correct option for each question."],
    questions: [
      {
        id: 1,
        text: "What is the value of 3² + 4²?",
        options: ["7", "12", "25", "5"],
        type: "objective",
        marks: 5,
      },
      {
        id: 2,
        text: "What is the square root of 144?",
        options: ["10", "11", "12", "13"],
        type: "objective",
        marks: 5,
      },
      {
        id: 3,
        text: "What is 15% of 200?",
        options: ["20", "25", "30", "35"],
        type: "objective",
        marks: 5,
      },
    ],
  },
  "mathematics-theory": {
    slug: "mathematics-theory",
    subject: "Mathematics",
    class: "JSS3",
    term: "First Term",
    date: "25 June 2025",
    time: "12:00 PM",
    duration: 120,
    type: "theory",
    instructions: [
      "Answer all questions.",
      "Show all steps in your calculations.",
      "State any formula used.",
    ],
    questions: [
      {
        id: 1,
        text: "Solve the equation: 3x - 7 = 2x + 5. Show all your steps.",
        type: "theory",
        marks: 10,
      },
      {
        id: 2,
        text: "The area of a rectangle is 48 cm². If the length is 8 cm, what is the width? Show your working.",
        type: "theory",
        marks: 8,
      },
    ],
  },
  "english-objective": {
    slug: "english-objective",
    subject: "English Language",
    class: "JSS3",
    term: "First Term",
    date: "28 June 2025",
    time: "10:00 AM",
    duration: 120,
    type: "objective",
    instructions: ["Answer all questions.", "Select the correct option."],
    questions: [
      {
        id: 1,
        text: "Which of the following is a correct plural form?",
        options: ["Childs", "Children", "Childrens", "Childes"],
        type: "objective",
        marks: 5,
      },
      {
        id: 2,
        text: 'What is the past tense of "go"?',
        options: ["Goed", "Went", "Gone", "Going"],
        type: "objective",
        marks: 5,
      },
      {
        id: 3,
        text: 'Which word is a synonym for "happy"?',
        options: ["Sad", "Joyful", "Angry", "Tired"],
        type: "objective",
        marks: 5,
      },
    ],
  },
  "english-theory": {
    slug: "english-theory",
    subject: "English Language",
    class: "JSS3",
    term: "First Term",
    date: "28 June 2025",
    time: "1:00 PM",
    duration: 90,
    type: "theory",
    instructions: [
      "Write neatly and legibly.",
      "Stay within the word limits where specified.",
      "Check your spelling and grammar.",
    ],
    questions: [
      {
        id: 1,
        text: 'Write a short essay on "The Importance of Education in My Community" (250-300 words).',
        type: "theory",
        marks: 20,
      },
      {
        id: 2,
        text: "Write a letter to your friend describing your school and your favorite subjects (200-250 words).",
        type: "theory",
        marks: 15,
      },
    ],
  },
  "biology-objective": {
    slug: "biology-objective",
    subject: "Biology",
    class: "JSS3",
    term: "First Term",
    date: "30 June 2025",
    time: "8:00 AM",
    duration: 120,
    type: "objective",
    instructions: ["Answer all questions.", "Choose the correct option."],
    questions: [
      {
        id: 1,
        text: "What is the largest organ in the human body?",
        options: ["Heart", "Liver", "Skin", "Brain"],
        type: "objective",
        marks: 5,
      },
      {
        id: 2,
        text: "Which blood type is known as the universal donor?",
        options: ["A", "B", "AB", "O"],
        type: "objective",
        marks: 5,
      },
      {
        id: 3,
        text: "What is the basic unit of life?",
        options: ["Cell", "Tissue", "Organ", "Organism"],
        type: "objective",
        marks: 5,
      },
      {
        id: 4,
        text: "Which of these is NOT a sense organ?",
        options: ["Eye", "Ear", "Nose", "Heart"],
        type: "objective",
        marks: 5,
      },
    ],
  },
  "biology-theory": {
    slug: "biology-theory",
    subject: "Biology",
    class: "JSS3",
    term: "First Term",
    date: "30 June 2025",
    time: "11:00 AM",
    duration: 90,
    type: "theory",
    instructions: [
      "Answer all questions.",
      "Label diagrams clearly.",
      "Use appropriate biological terms.",
    ],
    questions: [
      {
        id: 1,
        text: "Describe the human digestive system. Name the organs and explain their functions.",
        type: "theory",
        marks: 15,
      },
      {
        id: 2,
        text: "Explain the process of respiration in humans. Include the role of the respiratory system.",
        type: "theory",
        marks: 12,
      },
    ],
  },
};
