import { Question } from "@/types/question";

export const questionBankData: Question[] = [
  {
    id: 1,
    text: "What is the chemical symbol for water?",
    type: "objective",
    options: ["H2O", "CO2", "NaCl", "HCl"],
    correctAnswer: "H2O",
    marks: 5,
    subject: "Chemistry",
    class: "JSS3",
    difficulty: "easy",
  },
  {
    id: 2,
    text: "What is the atomic number of Carbon?",
    type: "objective",
    options: ["6", "12", "14", "8"],
    correctAnswer: "6",
    marks: 5,
    subject: "Chemistry",
    class: "JSS3",
    difficulty: "easy",
  },
  {
    id: 3,
    text: "Define an acid and give two examples with their chemical formulas.",
    type: "theory",
    options: [],
    correctAnswer: "",
    marks: 10,
    subject: "Chemistry",
    class: "JSS3",
    difficulty: "medium",
  },
  {
    id: 4,
    text: "Explain the process of photosynthesis and write the chemical equation.",
    type: "theory",
    options: [],
    correctAnswer: "",
    marks: 15,
    subject: "Chemistry",
    class: "JSS2",
    difficulty: "hard",
  },
  {
    id: 5,
    text: "What is the SI unit of force?",
    type: "objective",
    options: ["Newton", "Joule", "Watt", "Pascal"],
    correctAnswer: "Newton",
    marks: 5,
    subject: "Physics",
    class: "JSS3",
    difficulty: "easy",
  },
  {
    id: 6,
    text: "State Newton's three laws of motion.",
    type: "theory",
    options: [],
    correctAnswer: "",
    marks: 15,
    subject: "Physics",
    class: "SS1",
    difficulty: "hard",
  },
  {
    id: 7,
    text: "What is the value of 3² + 4²?",
    type: "objective",
    options: ["7", "12", "25", "5"],
    correctAnswer: "25",
    marks: 5,
    subject: "Mathematics",
    class: "JSS3",
    difficulty: "easy",
  },
  {
    id: 8,
    text: "Solve for x: 2x + 5 = 13",
    type: "theory",
    options: [],
    correctAnswer: "x = 4",
    marks: 10,
    subject: "Mathematics",
    class: "JSS2",
    difficulty: "medium",
  },
];

export const SUBJECTS = ["Chemistry", "Physics", "Mathematics", "Biology", "English Language"];
export const CLASSES = ["JSS1", "JSS2", "JSS3", "SS1", "SS2", "SS3"];
