import { NextRequest, NextResponse } from "next/server";
import { connectDB } from "@/lib/db";
import { requireAdmin } from "@/lib/api-guards";
import { Exam } from "@/lib/models/exam.model";
import { ClassLevel, ExamType, ExamStatus, Term } from "@/lib/models/constants";

// GET /api/admin/exams?class=JSS1&subject=<id>&term=First+Term&type=Objective&status=Scheduled
export async function GET(req: NextRequest) {
  const guard = await requireAdmin();
  if (!guard.ok) return guard.response;

  await connectDB();
  const params = req.nextUrl.searchParams;

  const filter: Record<string, unknown> = {};
  const classFilter = params.get("class") as ClassLevel | null;
  const subjectFilter = params.get("subject");
  const termFilter = params.get("term") as Term | null;
  const typeFilter = params.get("type") as ExamType | null;
  const statusFilter = params.get("status") as ExamStatus | null;

  if (classFilter) filter.class = classFilter;
  if (subjectFilter) filter.subject = subjectFilter;
  if (termFilter) filter.term = termFilter;
  if (typeFilter) filter.type = typeFilter;
  if (statusFilter) filter.status = statusFilter;

  const exams = await Exam.find(filter).populate("subject", "name code").sort({ examDate: -1 });

  return NextResponse.json({ exams });
}

// POST /api/admin/exams
// Body: { title, subject, class, term, academicYear, type, examDate,
// duration, instructions?, passingScore?, shuffleQuestions? }
// examCode is auto-generated by the Exam model's pre-save hook.
export async function POST(req: NextRequest) {
  const guard = await requireAdmin();
  if (!guard.ok) return guard.response;

  await connectDB();
  const body = await req.json();

  try {
    const exam = await Exam.create({
      title: body.title,
      subject: body.subject,
      class: body.class,
      term: body.term,
      academicYear: body.academicYear,
      type: body.type,
      examDate: body.examDate,
      duration: body.duration,
      instructions: body.instructions,
      passingScore: body.passingScore,
      shuffleQuestions: body.shuffleQuestions,
      createdBy: guard.session.user.id,
    });

    return NextResponse.json({ exam }, { status: 201 });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to create exam";
    // Duplicate exam (same subject+class+term+academicYear+type) hits the
    // unique index defined on the Exam schema.
    const isDuplicate = message.includes("duplicate key");
    return NextResponse.json(
      { error: isDuplicate ? "An exam like this already exists for this class/term" : message },
      { status: 400 },
    );
  }
}
