import { NextRequest, NextResponse } from "next/server";
import { connectDB } from "@/lib/db";
import { requireAdmin } from "@/lib/api-guards";
import { Exam, examClassFilter } from "@/lib/models/exam.model";
import { ClassLevel, ExamType, ExamStatus, Term } from "@/lib/models/constants";
import { syncExamStatus } from "@/lib/exam-status";

// GET /api/admin/exams?class=JSS1&subject=<id>&term=First+Term&type=Objective&status=Scheduled
export async function GET(req: NextRequest) {
  const guard = await requireAdmin();
  if (!guard.ok) return guard.response;

  await connectDB();
  const params = req.nextUrl.searchParams;

  const classFilter = params.get("class") as ClassLevel | null;
  const subjectFilter = params.get("subject");
  const termFilter = params.get("term") as Term | null;
  const typeFilter = params.get("type") as ExamType | null;
  const statusFilter = params.get("status") as ExamStatus | null;

  // status is applied AFTER the sync below, not as a DB query filter -
  // status is time-derived now, so a stale value in the database can't
  // be trusted at query time. Every other filter still runs in the query
  // itself since those fields don't drift on their own.
  // classFilter uses examClassFilter (an $or) since a general exam has no
  // single `class` value - it matches instead via its `classes` array.
  const filter: Record<string, unknown> = classFilter ? examClassFilter(classFilter) : {};
  if (subjectFilter) filter.subject = subjectFilter;
  if (termFilter) filter.term = termFilter;
  if (typeFilter) filter.type = typeFilter;

  const exams = await Exam.find(filter).populate("subject", "name code").sort({ examDate: -1 });

  // Recompute + persist each exam's status from examDate/duration before
  // returning - keeps status accurate for readers without needing a cron
  // job, and self-heals any exam whose status went stale since the last
  // time someone loaded it.
  await Promise.all(exams.map((exam) => syncExamStatus(exam)));

  const result = statusFilter ? exams.filter((e) => e.status === statusFilter) : exams;

  return NextResponse.json({ exams: result });
}

// POST /api/admin/exams
// Body: { title, subject, term, academicYear, type, examDate, duration,
// instructions?, passingScore?, shuffleQuestions?, isGeneral?,
// class?, classes?  }
// A class-specific exam (the default, isGeneral falsy) sends `class`.
// A general exam - one exam multiple classes can sit, e.g. a scholarship
// or aptitude test - sends `isGeneral: true` and `classes: string[]`
// instead; `class` is ignored in that case (the model clears it anyway).
// examCode is auto-generated by the Exam model's pre-save hook. status is
// intentionally NOT accepted here - it's always computed from
// examDate/duration (see lib/exam-status.ts), so a brand-new exam starts
// out as whatever computeExamStatus naturally derives (almost always
// "Scheduled" for a future date, but this stays correct even for a
// same-day exam created after its start time).
export async function POST(req: NextRequest) {
  const guard = await requireAdmin();
  if (!guard.ok) return guard.response;

  await connectDB();
  const body = await req.json();
  const isGeneral = Boolean(body.isGeneral);

  try {
    const exam = await Exam.create({
      title: body.title,
      subject: body.subject,
      isGeneral,
      class: isGeneral ? undefined : body.class,
      classes: isGeneral ? body.classes : undefined,
      term: body.term,
      academicYear: body.academicYear,
      type: body.type,
      examDate: body.examDate,
      duration: body.duration,
      instructions: body.instructions,
      passingScore: body.passingScore,
      shuffleQuestions: body.shuffleQuestions,
      createdBy: guard.session.user.id,
    });

    return NextResponse.json({ exam }, { status: 201 });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to create exam";
    // Duplicate exam (same subject+class+term+academicYear+type) hits the
    // unique index defined on the Exam schema.
    const isDuplicate = message.includes("duplicate key");
    return NextResponse.json(
      {
        error: isDuplicate
          ? isGeneral
            ? "A general exam with this title already exists for this subject/term"
            : "An exam like this already exists for this class/term"
          : message,
      },
      { status: 400 },
    );
  }
}
