import { NextRequest, NextResponse } from "next/server";
import mongoose from "mongoose";
import { connectDB } from "@/lib/db";
import { requireAdmin } from "@/lib/api-guards";
import { Exam, examClassFilter } from "@/lib/models/exam.model";
import { Subject } from "@/lib/models/subject.model";
import { ClassLevel, ExamType, ExamStatus, Term } from "@/lib/models/constants";
import { syncExamStatus } from "@/lib/exam-status";

// GET /api/admin/exams?class=JSS1&subject=<id>&term=First+Term&type=Objective&status=Scheduled
export async function GET(req: NextRequest) {
  const guard = await requireAdmin();
  if (!guard.ok) return guard.response;

  await connectDB();
  const params = req.nextUrl.searchParams;

  const classFilter = params.get("class") as ClassLevel | null;
  const subjectFilter = params.get("subject");
  const termFilter = params.get("term") as Term | null;
  const typeFilter = params.get("type") as ExamType | null;
  const statusFilter = params.get("status") as ExamStatus | null;

  // status is applied AFTER the sync below, not as a DB query filter -
  // status is time-derived now, so a stale value in the database can't
  // be trusted at query time. Every other filter still runs in the query
  // itself since those fields don't drift on their own.
  // classFilter uses examClassFilter (an $or) since a general exam has no
  // single `class` value - it matches instead via its `classes` array.
  const filter: Record<string, unknown> = classFilter ? examClassFilter(classFilter) : {};
  if (subjectFilter) filter.subject = subjectFilter;
  if (termFilter) filter.term = termFilter;
  if (typeFilter) filter.type = typeFilter;

  // Deliberately .lean() + resolve subject names ourselves here, instead
  // of .populate("subject", "name code"): populate (like any normal
  // query) casts every document's `subject` to ObjectId as it hydrates
  // results, and throws for the ENTIRE list if even one legacy/corrupt
  // document has a raw string there instead of a real ref. .lean() skips
  // that hydration step entirely, so one bad row degrades gracefully
  // instead of taking down the whole exams page.
  const exams = await Exam.find(filter).sort({ examDate: -1 }).lean();

  const validSubjectIds = Array.from(
    new Set(
      exams
        .map((e) => e.subject)
        .filter((s): s is mongoose.Types.ObjectId =>
          mongoose.Types.ObjectId.isValid(s as unknown as string),
        )
        .map((s) => s.toString()),
    ),
  );
  const subjectDocs = await Subject.find({ _id: { $in: validSubjectIds } })
    .select("name code")
    .lean();
  const subjectById = new Map(subjectDocs.map((s) => [s._id.toString(), s]));

  const examsWithResolvedSubject = exams.map((exam) => {
    const raw = exam.subject as unknown;
    const asString = String(raw ?? "");
    const resolved = mongoose.Types.ObjectId.isValid(asString)
      ? (subjectById.get(asString) ?? null)
      : null;
    return {
      ...exam,
      subject: resolved ?? { name: asString || "Unknown subject", code: "" },
    };
  });

  // Recompute + persist each exam's status from examDate/duration before
  // returning - keeps status accurate for readers without needing a cron
  // job, and self-heals any exam whose status went stale since the last
  // time someone loaded it. A malformed legacy exam (missing examDate or
  // duration) is left with whatever status it already has - see
  // syncExamStatus.
  await Promise.all(
    examsWithResolvedSubject.map(async (exam) => {
      exam.status = await syncExamStatus(exam);
    }),
  );

  const result = statusFilter
    ? examsWithResolvedSubject.filter((e) => e.status === statusFilter)
    : examsWithResolvedSubject;

  return NextResponse.json({ exams: result });
}

// POST /api/admin/exams
// Body: { title, subject, term, academicYear, type, examDate, duration,
// instructions?, passingScore?, shuffleQuestions?, isGeneral?,
// class?, classes?  }
// A class-specific exam (the default, isGeneral falsy) sends `class`.
// A general exam - one exam multiple classes can sit, e.g. a scholarship
// or aptitude test - sends `isGeneral: true` and `classes: string[]`
// instead; `class` is ignored in that case (the model clears it anyway).
// examCode is auto-generated by the Exam model's pre-save hook. status is
// intentionally NOT accepted here - it's always computed from
// examDate/duration (see lib/exam-status.ts), so a brand-new exam starts
// out as whatever computeExamStatus naturally derives (almost always
// "Scheduled" for a future date, but this stays correct even for a
// same-day exam created after its start time).
export async function POST(req: NextRequest) {
  const guard = await requireAdmin();
  if (!guard.ok) return guard.response;

  await connectDB();
  const body = await req.json();
  const isGeneral = Boolean(body.isGeneral);

  try {
    const exam = await Exam.create({
      title: body.title,
      subject: body.subject,
      isGeneral,
      class: isGeneral ? undefined : body.class,
      classes: isGeneral ? body.classes : undefined,
      term: body.term,
      academicYear: body.academicYear,
      type: body.type,
      examDate: body.examDate,
      duration: body.duration,
      instructions: body.instructions,
      passingScore: body.passingScore,
      shuffleQuestions: body.shuffleQuestions,
      createdBy: guard.session.user.id,
    });

    return NextResponse.json({ exam }, { status: 201 });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to create exam";
    // Duplicate exam (same subject+class+term+academicYear+type) hits the
    // unique index defined on the Exam schema.
    const isDuplicate = message.includes("duplicate key");
    return NextResponse.json(
      {
        error: isDuplicate
          ? isGeneral
            ? "A general exam with this title already exists for this subject/term"
            : "An exam like this already exists for this class/term"
          : message,
      },
      { status: 400 },
    );
  }
}
